# Generated by Django 6.0.5 on 2026-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
